### ISSUE TITLE
Script errors in Google Colab

### ISSUE THREAD

**Issue by MNC21** [danielkamen/Google-Analytics-Data-Export-to-BigQuery#1]
Hey Daniel, thanks so much for creating this. Trying to run this script in Colab and getting the following errors:

ValueError                                Traceback (most recent call last)
[<ipython-input-5-0203f2685f3d>](https://localhost:8080/#) in <cell line: 853>()
    852 
    853 if __name__ == '__main__':
--> 854     main()

AND 
![image](https://github.com/danielkamen/Google-Analytics-Data-Export-to-BigQuery/assets/88343468/c70e01a3-1cea-43d5-9e7c-9d907d681e10)

table_id must be a fully-qualified ID in standard SQL format, e.g., "project.dataset.table_id", got {myprojectid}.{mydatasetid}.Audience Demographics Gender_1

Pretty sure I populated all the placeholder values correctly. Any ideas what I'm doing wrong?

**Comment by danielkamen** [comment]
Hi there! Wow to be honest this is pretty cool, this is the first time somes reached out on any of my projects - thank you :)!


For your first issue, I believe that running the main method in google colab notebook is different. You instead should only need:
`main()` 
instead of the
`if __name__ == '__main__':`
    `    main()`
    
For your second issue, I'm not sure. Maybe that once you fix this other issue it will sort itself out. On that note, maybe try running this all inside one cell. I'm not experienced with python notebooks and best practices, so maybe theres an issue with the way you set up the project?

**Comment by MNC21** [comment]
Haha that's cool, glad to be your first! 

Removing the if statement did resolve and now the script runs without errors. I am executing the entire script in one cell but it completes in 0 seconds and no tables are created in the bigquery dataset. I tried running this locally but now getting the same error I was in colab. Either way, thanks for putting this out there! 

C:\Users\***\Desktop>python pyscript
C:\Users\***\Desktop\pyscript:8: SyntaxWarning: invalid escape sequence '\C'
  os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'D:\Chrome Downloads\***.json'
Traceback (most recent call last):
  File "C:\Users\***\Desktop\pyscript", line 853, in <module>
    main()
  File "C:\Users\***\Desktop\pyscript", line 830, in main
    bigquery.Client(project=project_id).get_table(f"{project_id}.{dataset_id}.{new_table_id}")
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\cloud\bigquery\client.py", line 1157, in get_table
    table_ref = _table_arg_to_table_ref(table, default_project=self.project)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\cloud\bigquery\table.py", line 3290, in _table_arg_to_table_ref
    value = TableReference.from_string(value, default_project=default_project)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\cloud\bigquery\table.py", line 283, in from_string
    ) = _helpers._parse_3_part_id(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\cloud\bigquery\_helpers.py", line 934, in _parse_3_part_id
    raise ValueError(
**ValueError: table_id must be a fully-qualified ID in standard SQL format, e.g., "project.dataset.table_id", got **-******.**-******.ga3v2.Audience Demographics Gender_1**

**Comment by danielkamen** [comment]
First issue might be how you have your file path. Mine was like this:
`'D:\\Chrome Downloads\\*.json'`.
For the other error, maybe you exported the key file incorrectly?
